name: API Bruno CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "explore/api-test-bruno/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: explore/api-test-bruno/scripts
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Bruno CLI
        run: npm i -g @usebruno/cli

      - name: Run Bruno tests
        env:
          BASE_URL: ${{ secrets.API_BASE_URL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: ./run-tests.sh ./templates/bruno staging

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bruno-reports
          path: explore/api-test-bruno/reports/**
