apiVersion: "v1.0.0"
kind: "DataProduct"
id: "{{DATA_PRODUCT_ID}}"
name: "{{DATA_PRODUCT_NAME}}"
status: "draft"
description:
  purpose: "{{PURPOSE}}"
team:
  name: "{{TEAM_NAME}}"
tags:
  - "{{TAG}}"
outputPorts:
  - name: "{{OUTPUT_PORT_NAME}}"
    version: "1"
    type: "{{PLATFORM}}"
    contractId: "{{CONTRACT_ID}}"
    customProperties:
      - property: "schema"
        value: "{{SCHEMA}}"
      - property: "catalog"
        value: "{{CATALOG}}"
      - property: "table"
        value: "{{TABLE}}"
      - property: "contractServer"
        value: "production"
      - property: "displayName"
        value: "{{TABLE}}"
      - property: "status"
        value: "draft"
      - property: "environment"
        value: "prod"
customProperties:
  - property: "icon"
    value: "{{PLATFORM}}"
  - property: "type"
    value: "consumer-aligned"
  - property: "visibility"
    value: "internal"
  - property: "dataProductBuilder"
    value: "https://github.com/entropy-data/dataproduct-builder-dbt"
